server:
  port: ${GATEWAY_PORT}
  tomcat:
    mbeanregistry:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    hostname: host.docker.internal
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://127.0.0.1:5500
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/members/login
            - Method=POST
          filters:
            - RewritePath=/member-server/(?<segment>.*), /$\{segment}
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/member-server/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader= Cookie, Set-Cookie
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/members/**
          filters:
            - AuthorizationFilter
            - RewritePath=/member-server/(?<segment>.*), /$\{segment}
        - id: order-server
          uri: lb://ORDER-SERVER
          predicates:
            - Path=/order-server/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/order-server/(?<segment>.*), /$\{segment}
        - id: order-server
          uri: lb://ORDER-SERVER
          predicates:
            - Path=/order-server/orders/**
            - Method=POST
          filters:
            - AuthorizationFilter
            - RewritePath=/order-server/(?<segment>.*), /$\{segment}
        - id: product-server
          uri: lb://PRODUCT-SERVER
          predicates:
            - Path=/product-server/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/product-server/(?<segment>.*), /$\{segment}
        - id: product-server
          uri: lb://PRODUCT-SERVER
          predicates:
            - Path=/product-server/products/**
            - Method=POST,GET
          filters:
            - RewritePath=/product-server/(?<segment>.*), /$\{segment}
        - id: auction-server
          uri: lb://AUCTION-SERVER
          predicates:
            - Path=/auction-server/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/auction-server/(?<segment>.*), /$\{segment}
        - id: auction-server
          uri: lb://AUCTION-SERVER
          predicates:
            - Path=/auction-server/auctions/**
            - Method=POST,GET
          filters:
            - RewritePath=/auction-server/(?<segment>.*), /$\{segment}
            - AuthorizationFilter

management:
  endpoints:
    web:
      exposure:
        include: ${GATEWAY_ACTUATOR_END_POINT}
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL}

logging:
  pattern:
    level: "%5p [%X{traceId:-}, %X{spanId:-}]"

jwt:
  secret:
    key: ${JWT_SECRET_KEY}